### ISSUE TITLE
Only include relevant sections when diffing

### ISSUE THREAD

**Issue by irony** [Klimatbyran/garbo#304] opened 2024-11-27 10:25 UTC
![Image](https://github.com/user-attachments/assets/76f2ca39-7719-4420-895c-669cb077c4d3)
We are not removing data here - we should either tell the AI to only focus on the initiatives section or remove the rest of the original data when comparing.

**Comment by Greenheart** [comment] 2024-11-27 10:35
Duplicate of #299, but this has a better description

**Closed** 2024-11-27 15:38 UTC
